services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_URL: "mysql2://user:password@db:3306/chat_app_development"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
      - redis
    command: bash -c "./wait.sh elasticsearch:9200 && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rake elasticsearch:create_indexes && bundle exec rails server -b 0.0.0.0"
  
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: "mysql2://user:password@db:3306/chat_app_development"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chat_app_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
volumes:
  db_data:
  es_data:
  redis_data:
